---
title: "R 笔记"
# author: "gly"
# date: "3/4/2022"
output: html_document
---

***
# 
***2022-3-4***

## R 工作路径设置


### 查看工作路径：
```{}
getwd()
```
### 设置工作路径：
#### 1. 使用代码
example:
```{}
setwd("~/bin/R/project1")       # RGui & RStudio皆可使用
```


#### 2. RStudio中创建项目：
File -- New Project -- Existing Directory，选择路径即可。

## 安装包及调用包

### 图形界面
在Packages中搜索选择所需的包（RGui & RStudio皆可）。

### 命令行
通过
```{}
install.packages("pkg_name")    # pkg_name为包的名字，双引号为必需
install.packages(c("package1", "package2"))   # 安装多个包
```
命令

### 使用包
使用
```{}
library("pkg_name")       # 双引号非必需
```
将包加载到当前R会话中，在当前R会话关闭前都可使用。

使用
```{}
library()
```
查看当前R库中存储的包。

#### 注[^*]：
另外可通过
```{}
install_github(...)
install_bitbucket(...)
```
安装未托管至CRAN的包

[^*]: 参考《R语言入门与实践》附录B。

## 求助
控制台中使用
```{}
?func_name
```
或者
```{}
help(func_name)
```
获得帮助

## R Markdown
* 先安包;

* 拓展名：.Rmd；

* 可支持编译为：.html, .pdf及Word文件。

  * ***注***：pdf及word格式输出需要相应的支持，如：***Tex Live, MS Word, Libre/Open Office***等。

\n
* 基本语法与***markdown***基本相同，支持*tex*格式的公式编辑；

### 插入代码块

* 插入代码块（多行或单行代码）：
````{}
```{}     # 若在{}中为设置，输入R，则该代码块将会被当成R语言代码执行，其后为命名，','后为设置，如‘echo=FALSE’（不打印代码）；留空则不执行
# code 
```
````
  &emsp;插入代码（该段使用多层嵌套，故可在输出代码块中显示 \```，否则将自动识别为代码块语法而进行渲染）
  
  &emsp;或者行前两个tab（注意该行前需空一行），可实现单行代码：
  
    # 这是一个单行代码


### 插入注释

  * 可用markdown语法：
```{}
[ ]: comment 
```
  &emsp; 进行注释，其中[ ]内可加任何东西，可组成表情包注释。

[-_-]: 这是一条注释

  * 也可使用html注释：
```{}
<!--也是注释-->

<!--
多
行
注
释
-->
```
<!-- 注释 -->

<!-- 
注释
-->


***


# 
***2022-3-11***

## R语言基础 I

### 数据类型
R的基本数据类型包括：

* 数值型(numeric)：包括整型数值、浮点型数值
* 逻辑型(logical)：包括Ture、False 
* 字符型(character)：包括单引号或双引号括起来的字符序列

R数据类型转换：

* 当数值型、逻辑型、字符型同时出现在同一向量中时，数据类型会按照逻辑型、数值型、字符型的顺序进行转换。
即：

  * 逻辑型和数值型同时出现在向量或矩阵中时，逻辑型数据转换为数值型，TRUE转换为1，FALSE转换为0；

  * 逻辑型、数值型、字符型同时出现在向量或矩阵中时，全部转换为字符型。


### 常量变量
R中的常量指：其值不能改变的量，包括：

* 数值常量(numeric constant)：包括所有整型(integer)、浮点型(float)、复数型数据(complex)；
* 字符常量(character constant)：包括所有的字符型数据；
* 逻辑常量(logical constant)：包括TRUE和FALSE两个逻辑型数据

R变量用于存储R对象。变量有变量名，亦称变量标识符(identifier)

* 变量名必须由字母、数字、下划线和句点（.）组成，且第一个字符不能是数字；若第一个字符是句点，第二个字符必须是字母；
* 中文环境下，汉字可作为合法变量名；
* 变量名区分大小写

### 保留字
R中，具有特定含义，不能用作变量标识符的单词， 称为保留字，主要包括：

* 函数定义及程序控制保留字： function, if, else, for, while, repeat, break, continue, next；
* 逻辑常量保留字： TRUE, FALSE；
* Inf：正无穷，比如1/0；
* NaN（Not a Number）：数学上不存在的数，比如0/0，两个正无穷相减；
* NA（Not Available）：尚未得到的数据，也称为缺失数据；
* NULL：空值对象。

## R语言基础II：数据结构
学习数据结构要关注两个方面：
一是***数据结构定义***； 二是***数据结构元素访问形式***。

综述：

* **向量**是R最基础的、 *“原子型”(atomic)*数据结构， “原子型”是指向量中各元素
*必须为相同类型数据*。

* R矩阵和数据框均为*二维“表格型”*数据结构，区别在于**矩阵元素**必须为或强制转化为*相同数据类型*，而**数据框**的各列可以是*包含不同数据类型的向量*。
数据框是R统计模型分析的基础。

* **列表**是R*最灵活*的数据结构，*可理解为“非原子型”向量*，列表的各个元素可
以是*向量、矩阵、数据框、 列表*。

### 向量(factor)
R中向量定义有两类方法。

* 一是通过基础通用的c()函数(c: concatenate，拼接)定义向量。
  * 基本语法为： c(…)，其中…表示可变长度输入参数，拟拼接到一起的数据对象，用英文输入逗号分隔。
  * 向量访问格式为：向量名[拟访问元素索引向量]。

* 二是有规律向量的快捷定义。 针对有规律向量，比如等差数列、格式有规律的字符串序列， R提供了更简洁的定义方式。主要涉及到R自带的
seq(), rep(), paste(), numeric(), character()函数

### 矩阵(matrix)
R中矩阵由函数matrix()定义， matrix()函数语法为：
matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE, dimnames = NULL)

* data：数据向量，默认值为缺失值NA,

* nrow：行数，默认值为1；

* ncol：列数，默认值为1；

* byrow：逻辑型，表示数据向量是否按行排列成矩阵，默认FALSE,即：默认按列填充；

* dimnames：矩阵行列名，默认为空值，或者为长度为2的列表，列表元素分别为字符型向量，表示行列名。

矩阵元素/子矩阵访问格式为： mat_name[row_index（行索引）, col_index（列索引）]。

**注：**

* letters与LETTERS为R内置向量，分别表示26位小写和大写拉丁字母。
* list()函数为列表定义函数，后文将介绍。

### 数据框(data frame)
R中数据框由函数data.frame()定义， data.frame()函数语法为：
data.frame(..., row_names = NULL, stringsAsFactors = TRUE)

* ...：可变长度输入参数，格式为value，或者tag=value；

* row_names：行名，默认为空；

* stringsAsFactors：字符型向量是否当作*因子*处理，默认为TRUE；

数据框的索引和矩阵类似： data.frame_name[row_index,col_index]； row_index、col_index可以替换为数据框行列。
也可通过如下形式访问数据框元素：

* data.frame_name$col_name，返回*列对应向量*；

* data.frame_name[[col_name]]，返回*列对应向量*；

* data.frame_name[col_name] ， 返回*特定列对应子数据框*。

注意体会不同索引方式的区别。 
比如:
```
d[[“age”]]        # 返回age向量
d[“age”]          # 返回只包含一个age字段的子数据框；
```
两种索引中，变量名age要用一对双引号括住；而使用$col_name访问时可以不要双引号;

采用双下标索引形式时，如果包含全部行或全部列，对应索引可以省略。


**注：**

* 因子为R中特殊的数据类型

* 向量和数据框在R控制台中的显示形式不一样，我们可以通过显示形式来倒推其类型

### 列表(list)

R中列表通过list()函数定义，基本语法为：list(…)

列表元素访问有两种格式：

* 一是list.name[index]，此时返回子列表；
* 二是list.name[[single.index]]，此时返回单个索引指标对应的数值或数据结构。

**注：**

* 若在定义列表时，给列表中的元素取了名字，则可使用该名字对列表进行访问。

